serverCert:
  privateKey:
    algorithm: ECDSA
    size: 256

clientCert:
  privateKey:
    algorithm: ECDSA
    size: 256

subject:
  organizations:
    - nextjs-grpc

vaultIssuerRef:
  name: vault-issuer
  serverEndpoint: https://vault.vault:8200
  secretName: <TF_POPULATED>
  caBundle: <TF_POPULATED>
  mountPath: <TF_POPULATED>

defaultDuration: 2h
defaultRenewBefore: 1h

caNamespaces:
  - api
  - ms
  - observability
