{{- $name := "api-server-cert" -}}
{{- $namespace := "api" -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  secretName: {{ $name }}
  issuerRef:
    name: {{ .Values.vaultIssuerRef.name | quote }}
  dnsNames:
    - {{ printf "%s.%s" "api" $namespace}}
  duration: {{ .Values.defaultDuration | quote }}
  privateKey:  {{ .Values.serverCert.privateKey | toYaml | nindent 4 }}
  usages: 
    - server auth
