{{ $files := .Files }}
{{ $ca_path := "files/intermediate" }}
{{ $cert_path := printf "%s/%s" $ca_path "certs/chain.crt"}}
{{ $key_path := printf "%s/%s" $ca_path "private/intermediate.key" }}
{{- range .Values.caNamespaces }}
apiVersion: v1
kind: Secret
metadata:
  name: intermediate-ca
  namespace: {{ . }}
data:
  tls.crt: {{ $files.Get $cert_path | b64enc }}
  tls.key: {{ $files.Get $key_path | b64enc }}
---
{{- end }}
