{{- $serviceName := "web-server" -}}
{{- $name := printf "ms-grpc-client-cert-for-%s" $serviceName -}}
{{- $namespace := "api" -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  secretName: {{ $name }}
  issuerRef:
    name: {{ .Values.vaultIssuerRef.name | quote }}
  dnsNames:
    - {{ printf "%s.%s" $serviceName $namespace }}
  duration: {{ .Values.defaultDuration | quote }}
  privateKey:  {{ .Values.clientCert.privateKey | toYaml | nindent 4 }}
  usages: 
    - client auth
